# Generated by Django 5.0.14 on 2026-04-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_parent_alter_organization_sort'),
        ('users', '0002_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='organization.organization', verbose_name='所属组织'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='岗位名称'),
        ),
    ]
