# Generated by Django 5.0.14 on 2026-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('name', models.CharField(max_length=100, verbose_name='组织名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='组织编码')),
                ('org_kind', models.CharField(choices=[('group', '集团'), ('company', '公司/分支机构'), ('department', '部门'), ('team', '小组')], default='department', max_length=20, verbose_name='组织类型')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='层级路径')),
                ('path_name', models.CharField(blank=True, default='', max_length=500, verbose_name='全路径名称')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='层级')),
                ('is_temporary', models.BooleanField(default=False, verbose_name='是否临时机构')),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '组织机构',
                'verbose_name_plural': '组织机构',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('name', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='岗位编码')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='岗位类别')),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位管理',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserOrganizationRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主组织')),
                ('relation_type', models.CharField(choices=[('primary', '主属'), ('part_time', '兼职'), ('borrowed', '借调'), ('temporary', '临时加入')], default='primary', max_length=20, verbose_name='关系类型')),
                ('duty', models.CharField(blank=True, default='', max_length=100, verbose_name='职务说明')),
                ('status', models.CharField(choices=[('active', '有效'), ('inactive', '失效')], default='active', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '用户组织关系',
                'verbose_name_plural': '用户组织关系',
                'default_permissions': (),
            },
        ),
    ]
