# Generated by Django 5.0.14 on 2026-04-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.organization', verbose_name='上级组织'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
    ]
