# Generated by Django 5.0.14 on 2026-04-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorganizationrelation',
            name='is_primary',
        ),
    ]
