# Generated by Django 5.0.14 on 2026-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='配置键')),
                ('value', models.TextField(blank=True, default='', verbose_name='配置值')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='配置分类')),
                ('is_secret', models.BooleanField(default=False, verbose_name='是否敏感')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
