# Generated by Django 5.0.14 on 2026-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='配置分类'),
        ),
        migrations.AlterField(
            model_name='configitem',
            name='is_secret',
            field=models.BooleanField(default=False, verbose_name='是否敏感'),
        ),
        migrations.AlterField(
            model_name='configitem',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='configitem',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='configitem',
            name='value',
            field=models.TextField(blank=True, default='', verbose_name='配置值'),
        ),
    ]
