# Generated by Django 5.0.14 on 2026-04-13 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='菜单编码')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, default='', max_length=255, verbose_name='组件路径')),
                ('menu_type', models.CharField(choices=[('directory', '目录'), ('menu', '菜单')], default='menu', max_length=20, verbose_name='菜单类型')),
                ('icon', models.CharField(blank=True, default='', max_length=100, verbose_name='图标')),
                ('visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_menus', to='contenttypes.contenttype', verbose_name='业务模型')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
