# Generated by Django 5.0.14 on 2026-04-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('menu', '0002_menu_code_menu_content_type_alter_menu_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='菜单编码'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='component',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='组件路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_menus', to='contenttypes.contenttype', verbose_name='业务模型'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('directory', '目录'), ('menu', '菜单')], default='menu', max_length=20, verbose_name='菜单类型'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(max_length=100, verbose_name='菜单名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menu', verbose_name='上级菜单'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='路由地址'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
