FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements/prod.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY backend /app
CMD ["gunicorn", "config.wsgi:application", "-b", "0.0.0.0:8000"]
