# Generated by Django 5.0.14 on 2026-04-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='角色编码'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='角色描述'),
        ),
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group', verbose_name='角色'),
        ),
    ]
