# Generated by Django 5.0.14 on 2026-04-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_groupprofile_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupprofile',
            options={'default_permissions': (), 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
    ]
