# Generated by Django 5.0.14 on 2026-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('target', models.CharField(max_length=100, verbose_name='目标对象')),
                ('content', models.TextField(blank=True, default='', verbose_name='操作内容')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
