# Generated by Django 5.0.14 on 2026-04-02 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target',
            field=models.CharField(max_length=100, verbose_name='目标对象'),
        ),
    ]
