# Generated by Django 5.0.14 on 2026-04-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menu', '0003_alter_menu_code_alter_menu_component_and_more'),
        ('organization', '0002_alter_organization_parent_alter_organization_sort'),
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdatascope',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_scope', to='auth.group', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='groupdatascope',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organization', verbose_name='指定组织'),
        ),
        migrations.AlterField(
            model_name='groupdatascope',
            name='scope_type',
            field=models.CharField(choices=[('self', '仅本人'), ('org', '本组织'), ('org_and_children', '本组织及下级'), ('all', '全部数据')], default='self', max_length=30, verbose_name='数据范围'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_menus', to='auth.group', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='groupmenu',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_roles', to='menu.menu', verbose_name='菜单'),
        ),
    ]
