# Generated by Django 5.0.14 on 2026-04-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_groupdatascope_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdatascope',
            name='scope_type',
            field=models.CharField(choices=[('self', '仅本人'), ('org', '本组织'), ('org_and_children', '本组织及下级'), ('custom', '自定义'), ('all', '全部数据')], default='self', max_length=30, verbose_name='数据范围'),
        ),
    ]
