# Generated by Django 5.0.14 on 2026-04-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_parent_alter_organization_sort'),
        ('rbac', '0003_alter_groupdatascope_scope_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupdatascope',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='groupmenu',
            options={'default_permissions': ()},
        ),
        migrations.AddField(
            model_name='groupdatascope',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='custom_data_scopes', to='organization.organization', verbose_name='自定义组织'),
        ),
    ]
