# Generated by Django 5.0.14 on 2026-04-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('perm_type', models.CharField(choices=[('api', 'API'), ('button', '按钮')], default='button', max_length=20, verbose_name='权限类型')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
