# Generated by Django 5.0.14 on 2026-04-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menu', '0003_alter_menu_code_alter_menu_component_and_more'),
        ('permission', '0002_menupermission_delete_permissionmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menupermission',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='menu.menu', verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='perm_type',
            field=models.CharField(choices=[('api', 'API'), ('button', '按钮')], default='button', max_length=20, verbose_name='权限类型'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_bindings', to='auth.permission', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='menupermission',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
    ]
