# Generated by Django 5.0.14 on 2026-04-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_alter_menupermission_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermission',
            options={'default_permissions': ()},
        ),
    ]
